### ISSUE TITLE
Headphone jack 3.5 for ALC298

### ISSUE THREAD

**Issue by truongtam-fudosan** [YBN-JUAN/X1C6-T470s-OpenCore-EFI#6]
Need Codec Commander in S/L/E
https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/downloads/
https://github.com/jardenliu/ALC298PlugFix

**Comment by YBN-JUAN** [comment]
> Need Codec Commander in S/L/E
> https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/downloads/
> https://github.com/jardenliu/ALC298PlugFix

Thanks for your advice, but the headphone seems worked properly with AppleALC and layout 29 on T470s.
